<?php
require_once 'config.php';
require_once 'fpdf.php';

// Get log_id from URL
$log_id = $_GET['log_id'] ?? '';

if (empty($log_id)) {
    die('Receipt ID is required');
}

// Get receipt data
$receipt_result = get_duty_receipt($log_id);

if (!$receipt_result['success']) {
    die($receipt_result['message']);
}

$receipt = $receipt_result['data'];

// Compute daily receipt number (resets each duty_date)
function get_daily_receipt_number($duty_date, $log_id) {
    global $conn;
    $stmt = $conn->prepare("SELECT COUNT(*) AS seq FROM duty_logs WHERE duty_date = ? AND status = 'Completed' AND log_id <= ?");
    $stmt->bind_param("si", $duty_date, $log_id);
    $stmt->execute();
    $res = $stmt->get_result();
    $row = $res->fetch_assoc();
    $seq = (int)($row['seq'] ?? 0);
    return max(1, $seq);
}

$daily_receipt_seq = get_daily_receipt_number($receipt['duty_date'], (int)$receipt['log_id']);
// Build date code like SEP0925
$duty_ts = strtotime($receipt['duty_date']);
$receipt_date_code = date('mdy', $duty_ts);

// Handle PDF download
if (isset($_GET['download']) && $_GET['download'] === 'pdf') {
    generate_receipt_pdf($receipt);
    exit();
}

// Handle PNG download
if (isset($_GET['download']) && $_GET['download'] === 'png') {
    generate_receipt_png($receipt);
    exit();
}

// Handle JPG download
if (isset($_GET['download']) && $_GET['download'] === 'jpg') {
    generate_receipt_jpg($receipt);
    exit();
}

// Function to generate PDF receipt
function generate_receipt_pdf($data) {
    $pdf = new FPDF();
    $pdf->AddPage();
    
    // Set font
    $pdf->SetFont('Arial', 'B', 16);
    
    // Header
    $pdf->Cell(0, 10, 'CEIT-SC Office Duty Receipt', 0, 1, 'C');
    $pdf->Ln(10);
    
    // Receipt details
    $pdf->SetFont('Arial', 'B', 12);
    global $daily_receipt_seq, $receipt_date_code;
    $pdf->Cell(0, 8, 'Receipt #: ' . $receipt_date_code . ' - #' . str_pad($daily_receipt_seq, 4, '0', STR_PAD_LEFT), 0, 1);
    $pdf->Cell(0, 8, 'Date Generated: ' . date('F j, Y g:i A'), 0, 1);
    $pdf->Ln(5);
    
    // Personal Information Section
    $pdf->SetFont('Arial', 'B', 14);
    $pdf->Cell(0, 8, 'Personal Information', 0, 1);
    $pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
    $pdf->Ln(5);
    
    $pdf->SetFont('Arial', '', 11);
    $pdf->Cell(50, 6, 'Full Name:', 0, 0);
    $pdf->Cell(0, 6, $data['full_name'], 0, 1);
    
    $pdf->Cell(50, 6, 'Student Number:', 0, 0);
    $pdf->Cell(0, 6, $data['student_number'], 0, 1);
    
    $pdf->Cell(50, 6, 'Committee:', 0, 0);
    $pdf->Cell(0, 6, $data['committee'], 0, 1);
    
    $pdf->Cell(50, 6, 'Position:', 0, 0);
    $pdf->Cell(0, 6, $data['position'], 0, 1);
    
    $pdf->Cell(50, 6, 'Course/Year/Section:', 0, 0);
    $pdf->Cell(0, 6, $data['course_year_section'], 0, 1);
    
    $pdf->Cell(50, 6, 'Age:', 0, 0);
    $pdf->Cell(0, 6, $data['age'] . ' years old', 0, 1);
    
    $pdf->Cell(50, 6, 'Contact Number:', 0, 0);
    $pdf->Cell(0, 6, $data['contact_number'], 0, 1);
    
    $pdf->Cell(50, 6, 'Address:', 0, 0);
    $pdf->MultiCell(0, 6, $data['address'], 0, 1);
    
    $pdf->Ln(5);
    
    // Duty Information Section
    $pdf->SetFont('Arial', 'B', 14);
    $pdf->Cell(0, 8, 'Duty Information', 0, 1);
    $pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
    $pdf->Ln(5);
    
    $pdf->SetFont('Arial', '', 11);
    $pdf->Cell(50, 6, 'Duty Date:', 0, 0);
    $pdf->Cell(0, 6, date('F j, Y', strtotime($data['duty_date'])), 0, 1);
    
    $pdf->Cell(50, 6, 'Time In:', 0, 0);
    $pdf->Cell(0, 6, date('g:i A', strtotime($data['time_in'])), 0, 1);
    
    $pdf->Cell(50, 6, 'Time Out:', 0, 0);
    $pdf->Cell(0, 6, date('g:i A', strtotime($data['time_out'])), 0, 1);
    
    $pdf->Cell(50, 6, 'Total Hours:', 0, 0);
    $pdf->SetFont('Arial', 'B', 11);
    $pdf->Cell(0, 6, format_hours_minutes($data['total_hours']), 0, 1);
    
    $pdf->Ln(10);
    
    // Footer
    $pdf->SetFont('Arial', 'I', 10);
    $pdf->Cell(0, 6, 'This receipt was automatically generated by the CEIT-SC Office Duty Tracker system.', 0, 1, 'C');
    $pdf->Cell(0, 6, 'Generated on ' . date('F j, Y \a\t g:i A'), 0, 1, 'C');
    
    // Output PDF
    $filename = 'duty_receipt_' . $data['student_number'] . '_' . date('Y-m-d', strtotime($data['duty_date'])) . '.pdf';
    $pdf->Output('D', $filename);
}

// Function to generate PNG receipt using HTML to image conversion
function generate_receipt_png($data) {
    // Create HTML content for the receipt
    $html = '
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 0;
                padding: 20px;
                background: white;
                width: 800px;
            }
            .receipt-container {
                background: white;
                border: 2px solid #BF6013;
                border-radius: 15px;
                padding: 30px;
                box-shadow: 0 4px 15px rgba(0,0,0,0.1);
            }
            .receipt-header {
                text-align: center;
                border-bottom: 3px solid #BF6013;
                padding-bottom: 20px;
                margin-bottom: 20px;
            }
            .logo {
                width: 80px;
                height: 80px;
                display: block;
                margin: 0 auto 10px auto;
            }
            .receipt-title {
                color: #BF6013;
                font-weight: bold;
                font-size: 28px;
                margin: 10px 0;
            }
            .receipt-subtitle {
                color: #666;
                font-size: 16px;
                margin-bottom: 10px;
            }
            .receipt-info {
                background: #f8f9fa;
                border-radius: 10px;
                padding: 20px;
                margin-bottom: 20px;
            }
            .info-row {
                display: flex;
                justify-content: space-between;
                padding: 8px 0;
                border-bottom: 1px solid #ddd;
            }
            .info-row:last-child {
                border-bottom: none;
            }
            .info-label {
                font-weight: bold;
                color: #333;
            }
            .info-value {
                color: #666;
            }
            .total-hours {
                background: linear-gradient(135deg, #BF6013 0%, #F4A441 100%);
                color: white;
                border-radius: 10px;
                padding: 20px;
                text-align: center;
                margin: 20px 0;
            }
            .total-hours h3 {
                font-size: 32px;
                margin: 0 0 10px 0;
            }
            .receipt-footer {
                text-align: center;
                margin-top: 30px;
                padding-top: 20px;
                border-top: 2px solid #eee;
                color: #666;
            }
        </style>
    </head>
    <body>
        <div class="receipt-container">
            <div class="receipt-header">
                <img src="CEIT-SCLogo.png" alt="CEIT-SC Logo" class="logo">
                <h1 class="receipt-title">DUTY COMPLETION RECEIPT</h1>
                <p class="receipt-subtitle">College of Engineering and Information Technology - Student Council</p>
            </div>
            
            <div class="receipt-info">
                <div class="info-row">
                    <span class="info-label">Receipt Number:</span>
                    <span class="info-value">' . $GLOBALS['receipt_date_code'] . ' - #' . str_pad($GLOBALS['daily_receipt_seq'], 4, '0', STR_PAD_LEFT) . '</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Officer Name:</span>
                    <span class="info-value">' . htmlspecialchars($data['full_name']) . '</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Student Number:</span>
                    <span class="info-value">' . htmlspecialchars($data['student_number']) . '</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Committee:</span>
                    <span class="info-value">' . htmlspecialchars($data['committee']) . '</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Position:</span>
                    <span class="info-value">' . htmlspecialchars($data['position']) . '</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Course, Year & Section:</span>
                    <span class="info-value">' . htmlspecialchars($data['course_year_section']) . '</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Duty Date:</span>
                    <span class="info-value">' . date('F j, Y', strtotime($data['duty_date'])) . '</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Time In:</span>
                    <span class="info-value">' . date('g:i A', strtotime($data['time_in'])) . '</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Time Out:</span>
                    <span class="info-value">' . date('g:i A', strtotime($data['time_out'])) . '</span>
                </div>
            </div>
            
            <div class="total-hours">
                <h3>' . format_hours_minutes($data['total_hours']) . '</h3>
                <p style="margin: 0;">Total Duty Hours Completed</p>
            </div>
            
            <div class="receipt-footer">
                <p><strong>Thank you for your service to CEIT-SC!</strong></p>
                <p style="margin: 5px 0;">Generated on ' . date('F j, Y \a\t g:i A') . '</p>
                <small>This is an automatically generated receipt.</small>
            </div>
        </div>
    </body>
    </html>';
    
    // Save HTML to temporary file
    $temp_html = tempnam(sys_get_temp_dir(), 'receipt_') . '.html';
    file_put_contents($temp_html, $html);
    
    // Generate PNG using wkhtmltoimage (if available) or alternative method
    $filename = 'duty_receipt_' . $data['student_number'] . '_' . date('Y-m-d', strtotime($data['duty_date'])) . '.png';
    
    // Try using wkhtmltoimage first
    $output_path = tempnam(sys_get_temp_dir(), 'receipt_') . '.png';
    $command = "wkhtmltoimage --width 800 --height 1000 --quality 100 '$temp_html' '$output_path' 2>/dev/null";
    exec($command, $output, $return_code);
    
    if ($return_code === 0 && file_exists($output_path)) {
        // Success with wkhtmltoimage
        header('Content-Type: image/png');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Content-Length: ' . filesize($output_path));
        readfile($output_path);
        unlink($output_path);
        unlink($temp_html);
    } else {
        // Fallback: Use browser-based screenshot via JavaScript
        // Return the HTML with JavaScript to capture screenshot
        echo '
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>
            <style>
                body { margin: 0; padding: 20px; font-family: Arial, sans-serif; }
                .download-info { text-align: center; margin-bottom: 20px; padding: 20px; background: #f0f0f0; border-radius: 10px; }
                .btn { background: #BF6013; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; margin: 5px; }
                .btn:hover { background: #a0500f; }
            </style>
        </head>
        <body>
            <div class="download-info">
                <h3>PNG Download</h3>
                <p>Click the button below to download your receipt as a PNG image.</p>
                <button class="btn" onclick="downloadPNG()">Download PNG</button>
                <button class="btn" onclick="window.history.back()">Go Back</button>
            </div>
            
            <div id="receipt-content">
                ' . $html . '
            </div>
            
            <script>
                function downloadPNG() {
                    const element = document.getElementById("receipt-content");
                    html2canvas(element, {
                        width: 800,
                        height: 1000,
                        scale: 2,
                        useCORS: true,
                        backgroundColor: "#ffffff"
                    }).then(canvas => {
                        const link = document.createElement("a");
                        link.download = "' . $filename . '";
                        link.href = canvas.toDataURL("image/png");
                        link.click();
                    });
                }
            </script>
        </body>
        </html>';
        unlink($temp_html);
    }
}

// Function to generate JPG receipt using HTML to image conversion
function generate_receipt_jpg($data) {
    // Reuse the same HTML as PNG (includes logo)
    // Create HTML content for the receipt
    $html = '
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 0;
                padding: 20px;
                background: white;
                width: 800px;
            }
            .receipt-container {
                background: white;
                border: 2px solid #BF6013;
                border-radius: 15px;
                padding: 30px;
                box-shadow: 0 4px 15px rgba(0,0,0,0.1);
            }
            .receipt-header {
                text-align: center;
                border-bottom: 3px solid #BF6013;
                padding-bottom: 20px;
                margin-bottom: 20px;
            }
            .logo {
                width: 80px;
                height: 80px;
                display: block;
                margin: 0 auto 10px auto;
            }
            .receipt-title {
                color: #BF6013;
                font-weight: bold;
                font-size: 28px;
                margin: 10px 0;
            }
            .receipt-subtitle {
                color: #666;
                font-size: 16px;
                margin-bottom: 10px;
            }
            .receipt-info {
                background: #f8f9fa;
                border-radius: 10px;
                padding: 20px;
                margin-bottom: 20px;
            }
            .info-row {
                display: flex;
                justify-content: space-between;
                padding: 8px 0;
                border-bottom: 1px solid #ddd;
            }
            .info-row:last-child {
                border-bottom: none;
            }
            .info-label {
                font-weight: bold;
                color: #333;
            }
            .info-value {
                color: #666;
            }
            .total-hours {
                background: linear-gradient(135deg, #BF6013 0%, #F4A441 100%);
                color: white;
                border-radius: 10px;
                padding: 20px;
                text-align: center;
                margin: 20px 0;
            }
            .total-hours h3 {
                font-size: 32px;
                margin: 0 0 10px 0;
            }
            .receipt-footer {
                text-align: center;
                margin-top: 30px;
                padding-top: 20px;
                border-top: 2px solid #eee;
                color: #666;
            }
        </style>
    </head>
    <body>
        <div class="receipt-container">
            <div class="receipt-header">
                <img src="CEIT-SCLogo.png" alt="CEIT-SC Logo" class="logo">
                <h1 class="receipt-title">DUTY COMPLETION RECEIPT</h1>
                <p class="receipt-subtitle">College of Engineering and Information Technology - Student Council</p>
            </div>
            
            <div class="receipt-info">
                <div class="info-row">
                    <span class="info-label">Receipt Number:</span>
                    <span class="info-value">' . $GLOBALS['receipt_date_code'] . ' - #' . str_pad($GLOBALS['daily_receipt_seq'], 4, '0', STR_PAD_LEFT) . '</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Officer Name:</span>
                    <span class="info-value">' . htmlspecialchars($data['full_name']) . '</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Student Number:</span>
                    <span class="info-value">' . htmlspecialchars($data['student_number']) . '</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Committee:</span>
                    <span class="info-value">' . htmlspecialchars($data['committee']) . '</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Position:</span>
                    <span class="info-value">' . htmlspecialchars($data['position']) . '</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Course, Year & Section:</span>
                    <span class="info-value">' . htmlspecialchars($data['course_year_section']) . '</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Duty Date:</span>
                    <span class="info-value">' . date('F j, Y', strtotime($data['duty_date'])) . '</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Time In:</span>
                    <span class="info-value">' . date('g:i A', strtotime($data['time_in'])) . '</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Time Out:</span>
                    <span class="info-value">' . date('g:i A', strtotime($data['time_out'])) . '</span>
                </div>
            </div>
            
            <div class="total-hours">
                <h3>' . format_hours_minutes($data['total_hours']) . '</h3>
                <p style="margin: 0;">Total Duty Hours Completed</p>
            </div>
            
            <div class="receipt-footer">
                <p><strong>Thank you for your service to CEIT-SC!</strong></p>
                <p style="margin: 5px 0;">Generated on ' . date('F j, Y \a\t g:i A') . '</p>
                <small>This is an automatically generated receipt.</small>
            </div>
        </div>
    </body>
    </html>';
    
    // Save HTML to temporary file
    $temp_html = tempnam(sys_get_temp_dir(), 'receipt_') . '.html';
    file_put_contents($temp_html, $html);
    
    // Generate JPG using wkhtmltoimage (if available) or alternative method
    $filename = 'duty_receipt_' . $data['student_number'] . '_' . date('Y-m-d', strtotime($data['duty_date'])) . '.jpg';
    
    // Try using wkhtmltoimage first
    $output_path = tempnam(sys_get_temp_dir(), 'receipt_') . '.jpg';
    $command = "wkhtmltoimage --width 800 --height 1000 --quality 100 '$temp_html' '$output_path' 2>/dev/null";
    exec($command, $output, $return_code);
    
    if ($return_code === 0 && file_exists($output_path)) {
        // Success with wkhtmltoimage
        header('Content-Type: image/jpeg');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Content-Length: ' . filesize($output_path));
        readfile($output_path);
        unlink($output_path);
        unlink($temp_html);
    } else {
        // Fallback: Use browser-based screenshot via JavaScript
        // Return the HTML with JavaScript to capture screenshot
        echo '
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>
            <style>
                body { margin: 0; padding: 20px; font-family: Arial, sans-serif; }
                .download-info { text-align: center; margin-bottom: 20px; padding: 20px; background: #f0f0f0; border-radius: 10px; }
                .btn { background: #BF6013; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; margin: 5px; }
                .btn:hover { background: #a0500f; }
            </style>
        </head>
        <body>
            <div class="download-info">
                <h3>JPG Download</h3>
                <p>Click the button below to download your receipt as a JPG image.</p>
                <button class="btn" onclick="downloadJPG()">Download JPG</button>
                <button class="btn" onclick="window.history.back()">Go Back</button>
            </div>
            
            <div id="receipt-content">
                ' . $html . '
            </div>
            
            <script>
                function downloadJPG() {
                    const element = document.getElementById("receipt-content");
                    html2canvas(element, {
                        width: 800,
                        height: 1000,
                        scale: 2,
                        useCORS: true,
                        backgroundColor: "#ffffff"
                    }).then(canvas => {
                        const link = document.createElement("a");
                        link.download = "' . $filename . '";
                        link.href = canvas.toDataURL("image/jpeg", 0.92);
                        link.click();
                    });
                }
            </script>
        </body>
        </html>';
        unlink($temp_html);
    }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Duty Receipt - CEIT-SC Office Duty Tracker</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <style>
        @media print {
            .no-print { display: none !important; }
            body { background: white !important; }
            .receipt-container { box-shadow: none !important; }
        }
        
        body {
            background: linear-gradient(135deg, #1C1C1C 0%, #2E2E2E 50%, #BF6013 100%);
            min-height: 100vh;
            padding: 2rem 0;
        }
        
        .receipt-container {
            background: white;
            border-radius: 20px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.2);
            padding: 3rem;
            max-width: 800px;
            margin: 0 auto;
        }
        
        .receipt-header {
            text-align: center;
            border-bottom: 3px solid #BF6013;
            padding-bottom: 2rem;
            margin-bottom: 2rem;
        }
        
        .logo {
            width: 80px;
            height: 80px;
            margin-bottom: 1rem;
        }
        
        .receipt-title {
            color: #BF6013;
            font-weight: 800;
            font-size: 2rem;
            margin-bottom: 0.5rem;
        }
        
        .receipt-subtitle {
            color: #666;
            font-size: 1.1rem;
        }
        
        .receipt-info {
            background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);
            border-radius: 15px;
            padding: 1.5rem;
            margin-bottom: 2rem;
        }
        
        .info-row {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 0.75rem 0;
            border-bottom: 1px solid rgba(0,0,0,0.1);
        }
        
        .info-row:last-child {
            border-bottom: none;
        }
        
        .info-label {
            font-weight: 600;
            color: #333;
        }
        
        .info-value {
            color: #666;
            font-weight: 500;
        }
        
        .total-hours {
            background: linear-gradient(135deg, #BF6013 0%, #F4A441 100%);
            color: white;
            border-radius: 15px;
            padding: 1.5rem;
            text-align: center;
            margin: 2rem 0;
        }
        
        .total-hours h3 {
            font-size: 2.5rem;
            font-weight: 800;
            margin-bottom: 0.5rem;
        }
        
        .receipt-footer {
            text-align: center;
            margin-top: 3rem;
            padding-top: 2rem;
            border-top: 2px solid #eee;
            color: #666;
        }
        
        .btn-download {
            background: linear-gradient(135deg, #BF6013 0%, #F4A441 100%);
            border: none;
            border-radius: 15px;
            padding: 12px 30px;
            color: white;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            transition: all 0.3s ease;
            text-decoration: none;
            display: inline-block;
        }
        
        .btn-download:hover {
            transform: translateY(-3px);
            box-shadow: 0 15px 35px rgba(191, 96, 19, 0.4);
            color: white;
            text-decoration: none;
        }
        
        .btn-secondary {
            background: #6c757d;
            border: none;
            border-radius: 15px;
            padding: 12px 30px;
            color: white;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            transition: all 0.3s ease;
            text-decoration: none;
            display: inline-block;
        }
        
        .btn-secondary:hover {
            background: #5a6268;
            transform: translateY(-3px);
            color: white;
            text-decoration: none;
        }
        
        .badge {
            font-size: 0.9rem !important;
            padding: 0.5rem 0.75rem !important;
            font-weight: 600 !important;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="receipt-container">
            
            <!-- Receipt Header -->
            <div class="receipt-header">
                <img src="CEIT-SCLogo.png" alt="CEIT-SC Logo" class="logo">
                <h1 class="receipt-title">DUTY COMPLETION RECEIPT</h1>
                <p class="receipt-subtitle">College of Engineering and Information Technology - Student Council</p>
            </div>
            
            <!-- Receipt Information -->
            <div class="receipt-info">
                <div class="info-row">
                    <span class="info-label">Receipt Number:</span>
                    <span class="info-value"><?php echo $receipt_date_code . ' - #' . str_pad($daily_receipt_seq, 4, '0', STR_PAD_LEFT); ?></span>
                </div>
                <div class="info-row">
                    <span class="info-label">Officer Name:</span>
                    <span class="info-value"><?php echo htmlspecialchars($receipt['full_name']); ?></span>
                </div>
                <div class="info-row">
                    <span class="info-label">Student Number:</span>
                    <span class="info-value"><?php echo htmlspecialchars($receipt['student_number']); ?></span>
                </div>
                <div class="info-row">
                    <span class="info-label">Committee:</span>
                    <span class="info-value"><?php echo htmlspecialchars($receipt['committee']); ?></span>
                </div>
                <div class="info-row">
                    <span class="info-label">Position:</span>
                    <span class="info-value"><?php echo htmlspecialchars($receipt['position']); ?></span>
                </div>
                <div class="info-row">
                    <span class="info-label">Course, Year & Section:</span>
                    <span class="info-value"><?php echo htmlspecialchars($receipt['course_year_section']); ?></span>
                </div>
                <div class="info-row">
                    <span class="info-label">Duty Date:</span>
                    <span class="info-value"><?php echo date('F j, Y', strtotime($receipt['duty_date'])); ?></span>
                </div>
                <div class="info-row">
                    <span class="info-label">Time In:</span>
                    <span class="info-value"><?php echo date('g:i A', strtotime($receipt['time_in'])); ?></span>
                </div>
                <div class="info-row">
                    <span class="info-label">Time Out:</span>
                    <span class="info-value"><?php echo date('g:i A', strtotime($receipt['time_out'])); ?></span>
                </div>
            </div>
            
            <!-- Total Hours -->
            <div class="total-hours">
                <h3><?php echo format_hours_minutes($receipt['total_hours']); ?></h3>
                <p class="mb-0">Total Duty Hours Completed</p>
            </div>
            
            <!-- Receipt Footer -->
            <div class="receipt-footer">
                <p><strong>Thank you for your service to CEIT-SC!</strong></p>
                <p class="mb-0">Generated on <?php echo date('F j, Y \a\t g:i A'); ?></p>
                <small class="text-muted">This is an automatically generated receipt.</small>
            </div>
        </div>

        <!-- Action Buttons BELOW the receipt -->
        <div class="text-center mt-4 no-print">
            <a href="?log_id=<?php echo $receipt['log_id']; ?>&download=pdf" class="btn-download me-2">
                <i class="fas fa-file-pdf me-2"></i>Download PDF
            </a>
            <a href="?log_id=<?php echo $receipt['log_id']; ?>&download=png" class="btn-download me-2">
                <i class="fas fa-image me-2"></i>Download PNG
            </a>
            <a href="?log_id=<?php echo $receipt['log_id']; ?>&download=jpg" class="btn-download me-2">
                <i class="fas fa-image me-2"></i>Download JPG
            </a>
            <a href="index.php" class="btn-secondary">
                <i class="fas fa-arrow-left me-2"></i>Back to Dashboard
            </a>
        </div>
    </div>
</body>
</html>
